tabs:
  credentials:
    display: Credentials
    sections:
      -
        fields:
          -
            handle: accounts
            field:
              min_rows: 1
              add_row: 'Add Account'
              fullscreen: false
              type: grid
              display: 'Accounts'
              fields:
                -
                  handle: handle
                  field:
                    type: text
                    display: Handle
                    width: 50
                    validate:
                      - required
                -
                  handle: access_token
                  field:
                    type: text
                    display: 'Access Token'
                    width: 50
                    validate:
                      - required
title: Config
